#!/bin/bash

ARCH_="$1"
.github/extract-foreign.sh "zlib1g-dev:${ARCH_}"
.github/extract-foreign.sh "zlib1g:${ARCH_}"
.github/extract-foreign.sh "libpng-dev:${ARCH_}"
.github/extract-foreign.sh "libpng[0-9]*:${ARCH_}"
.github/extract-foreign.sh "libsdl1.2-dev:${ARCH_}"
.github/extract-foreign.sh "libsdl1.2debian:${ARCH_}"
# endless libsdl deps
.github/extract-foreign.sh "libasound[2-9]:${ARCH_}"
.github/extract-foreign.sh "libpulse[0-9]:${ARCH_}"
.github/extract-foreign.sh "libx11-[6-9]:${ARCH_}"
.github/extract-foreign.sh "libx11-dev:${ARCH_}"
.github/extract-foreign.sh "x11proto-dev"
.github/extract-foreign.sh "libxext[6-9]:${ARCH_}"
.github/extract-foreign.sh "libxcb1:${ARCH_}"
.github/extract-foreign.sh "libxau[6-9]:${ARCH_}"
.github/extract-foreign.sh "libxdmcp[6-9]:${ARCH_}"
.github/extract-foreign.sh "libcaca[0-9]:${ARCH_}"
.github/extract-foreign.sh "libdbus-[0-9]*:${ARCH_}"
.github/extract-foreign.sh "libslang[2-9]:${ARCH_}"
.github/extract-foreign.sh "libncursesw[6-9]:${ARCH_}"
.github/extract-foreign.sh "libtinfo[6-9]:${ARCH_}"
.github/extract-foreign.sh "libsystemd[0-9]:${ARCH_}"
.github/extract-foreign.sh "libwrap[0-9]:${ARCH_}"
.github/extract-foreign.sh "libsndfile[0-9]:${ARCH_}"
.github/extract-foreign.sh "libasyncns[0-9]:${ARCH_}"
.github/extract-foreign.sh "libbsd[0-9]:${ARCH_}"
.github/extract-foreign.sh "liblzma[0-9]:${ARCH_}"
.github/extract-foreign.sh "liblz[4-9]-*:${ARCH_}"
.github/extract-foreign.sh "libgcrypt[0-9]*:${ARCH_}"
.github/extract-foreign.sh "libflac[0-9]:${ARCH_}"
.github/extract-foreign.sh "libogg[0-9]:${ARCH_}"
.github/extract-foreign.sh "libvorbis[0-9]*:${ARCH_}"
.github/extract-foreign.sh "libvorbisenc[2-9]:${ARCH_}"
.github/extract-foreign.sh "libgpg-error[0-9]:${ARCH_}"
