USE_GTK=1
USE_ALSA = 1
USE_OSS=0
LDFLAGS += $(shell pkg-config --libs hildon-1 libpulse)
CFLAGS += -march=armv7-a -mcpu=cortex-a8 -mtune=cortex-a8 -mfloat-abi=softfp -ffast-math -O3 \
	-mfpu=neon -funsafe-math-optimizations \
	-mstructure-size-boundary=32 -falign-functions=32 -falign-loops
