void cvt_s_w(int *source,float *dest);
void cvt_d_w(int *source,double *dest);
void cvt_s_l(long long *source,float *dest);
void cvt_d_l(long long *source,double *dest);
void cvt_w_s(float *source,int *dest);
void cvt_w_d(double *source,int *dest);
void cvt_l_s(float *source,long long *dest);
void cvt_l_d(double *source,long long *dest);
void cvt_d_s(float *source,double *dest);
void cvt_s_d(double *source,float *dest);
void round_l_s(float *source,long long *dest);
void round_w_s(float *source,int *dest);
void trunc_l_s(float *source,long long *dest);
void trunc_w_s(float *source,int *dest);
void ceil_l_s(float *source,long long *dest);
void ceil_w_s(float *source,int *dest);
void floor_l_s(float *source,long long *dest);
void floor_w_s(float *source,int *dest);
void round_l_d(double *source,long long *dest);
void round_w_d(double *source,int *dest);
void trunc_l_d(double *source,long long *dest);
void trunc_w_d(double *source,int *dest);
void ceil_l_d(double *source,long long *dest);
void ceil_w_d(double *source,int *dest);
void floor_l_d(double *source,long long *dest);
void floor_w_d(double *source,int *dest);
void c_f_s();
void c_un_s(float *source,float *target);
void c_eq_s(float *source,float *target);
void c_ueq_s(float *source,float *target);
void c_olt_s(float *source,float *target);
void c_ult_s(float *source,float *target);
void c_ole_s(float *source,float *target);
void c_ule_s(float *source,float *target);
void c_sf_s(float *source,float *target);
void c_ngle_s(float *source,float *target);
void c_seq_s(float *source,float *target);
void c_ngl_s(float *source,float *target);
void c_lt_s(float *source,float *target);
void c_nge_s(float *source,float *target);
void c_le_s(float *source,float *target);
void c_ngt_s(float *source,float *target);
void c_f_d();
void c_un_d(double *source,double *target);
void c_eq_d(double *source,double *target);
void c_ueq_d(double *source,double *target);
void c_olt_d(double *source,double *target);
void c_ult_d(double *source,double *target);
void c_ole_d(double *source,double *target);
void c_ule_d(double *source,double *target);
void c_sf_d(double *source,double *target);
void c_ngle_d(double *source,double *target);
void c_seq_d(double *source,double *target);
void c_ngl_d(double *source,double *target);
void c_lt_d(double *source,double *target);
void c_nge_d(double *source,double *target);
void c_le_d(double *source,double *target);
void c_ngt_d(double *source,double *target);
void add_s(float *source1,float *source2,float *target);
void sub_s(float *source1,float *source2,float *target);
void mul_s(float *source1,float *source2,float *target);
void div_s(float *source1,float *source2,float *target);
void sqrt_s(float *source,float *target);
void abs_s(float *source,float *target);
void mov_s(float *source,float *target);
void neg_s(float *source,float *target);
void add_d(double *source1,double *source2,double *target);
void sub_d(double *source1,double *source2,double *target);
void mul_d(double *source1,double *source2,double *target);
void div_d(double *source1,double *source2,double *target);
void sqrt_d(double *source,double *target);
void abs_d(double *source,double *target);
void mov_d(double *source,double *target);
void neg_d(double *source,double *target);
