.\"                                      Hey, EMACS: -*- nroff -*-
.TH PCSX 1 "October 01, 2005"
.SH NAME
pcsx - Playstation emulator
.SH SYPNOSIS
.B pcsx
.I [options] [file]
.SH DESCRIPTION
PCSX is a plugin-based Playstation emulator able to play most PSX games. It provides CPU, BIOS, and basic system emulation and relies on plugins for sound, input, and graphics emulation.
.PP
.SH OPTIONS
.B -runcd
Runs CD-ROM from drive
.TP
.B -cdfile FILE
Runs a CD image file
.TP
.B -nogui
Don't load the GUI
.TP
.B -cfg FILE
Specify a different config file
.TP
.B -psxout
Enable PSX output
.TP
.B -load STATENUM
Loads savestate STATENUM
.TP
.B -help (-h)
Display help message
.TP
.SH AUTHOR
pcsx was written by Linuzappz <linuzappz@pcsx.net>. PCSX-df was written by Ryan Schultz <schultz.ryan@gmail.com> and Andrew Burton <adb@iinet.net.au>.
This manual page was written by Ryan Schultz <schultz.ryan@gmail.com> for the Debian Project.
