CC = $(CROSS_COMPILE)gcc
CXX = $(CROSS_COMPILE)g++
CC_ = $(CROSS_COMPILE)gcc

ARCH = $(shell $(CC) -v 2>&1 | grep -i 'target:' | awk '{print $$2}' | awk -F '-' '{print $$1}')

CFLAGS += -ggdb -Wall -DTEST
CFLAGS += -O2
ifeq "$(ARCH)" "arm"
CFLAGS += -mcpu=cortex-a8 -mtune=cortex-a8 -mfpu=neon -mfloat-abi=softfp
endif
ifeq "$(ARCH)" "x86_64"
CFLAGS += -m32
endif

# test_neon
TARGETS = test_peops test_unai
SRC += test.c

all: $(TARGETS)

test_neon: SRC += psx_gpu_if.c
test_neon: CFLAGS += -fno-strict-aliasing
test_peops: SRC += peops_if.c
test_peops: CFLAGS += -fno-strict-aliasing
test_unai: SRC += unai_if.cpp
test_unai: CC_ = $(CXX)

$(TARGETS): $(SRC)
	$(CC_) -o $@ $(SRC) $(CFLAGS) $(LDFLAGS)

clean:
	$(RM) $(TARGETS)
