#ifndef UI_FEATURES_H
#define UI_FEATURES_H

#define MENU_BIOS_PATH "pcsx_rearmed/bios/"
#define MENU_SHOW_VARSCALER 0
#define MENU_SHOW_VOUTMODE 0
#define MENU_SHOW_SCALER2 1
#define MENU_SHOW_NUBS_BTNS 0
#define MENU_SHOW_VIBRATION 1
#define MENU_SHOW_DEADZONE 1
#define MENU_SHOW_MINIMIZE 0
#define MENU_SHOW_FULLSCREEN 0
#define MENU_SHOW_VOLUME 1

#endif // UI_FEATURES_H
